typescript 
import { Empleado } from '@/hooks/useLocalStorage';

const empleadosIniciales: Empleado[] = [
  {
    id: '1',
    nombre: 'Carlos',
    apellido: 'Rodríguez',
    documento: '12345678',
    tipoDocumento: 'cedula',
    cargo: 'Ingeniero Civil',
    telefono: '3001234567',
    email: 'carlos.rodriguez@constructoracsrsas.com',
    salario: 4500000,
    fechaIngreso: '2023-01-15',
    activo: true,
    documentos: [],
  },
  {
    id: '2',
    nombre: 'María',
    apellido: 'González',
    documento: '87654321',
    tipoDocumento: 'cedula',
    cargo: 'Arquitecta',
    telefono: '3009876543',
    email: 'maria.gonzalez@constructoracsrsas.com',
    salario: 4200000,
    fechaIngreso: '2023-02-01',
    activo: true,
    documentos: [],
  },
  {
    id: '3',
    nombre: 'Luis',
    apellido: 'Martínez',
    documento: '11223344',
    tipoDocumento: 'cedula',
    cargo: 'Maestro de Obra',
    telefono: '3005566778',
    email: 'luis.martinez@constructoracsrsas.com',
    salario: 2800000,
    fechaIngreso: '2022-11-10',
    activo: true,
    documentos: [],
  },
];
